# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LaunchVehicle.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13LaunchVehicle.proto\"%\n\x0eVehicleRequest\x12\x13\n\x0bvehicleName\x18\x01 \x01(\t\"p\n\x15VehicleLaunchResponse\x12\x14\n\x0cresponseCode\x18\x01 \x01(\x05\x12\x17\n\x0fresponseMessage\x18\x02 \x01(\t\x12\x18\n\x0btimeToOrbit\x18\x03 \x01(\x05H\x00\x88\x01\x01\x42\x0e\n\x0c_timeToOrbit\"F\n\x15\x44\x65ployPayloadResponse\x12\x14\n\x0cresponseCode\x18\x01 \x01(\x05\x12\x17\n\x0fresponseMessage\x18\x02 \x01(\t\"@\n\x0f\x44\x65orbitResponse\x12\x14\n\x0cresponseCode\x18\x01 \x01(\x05\x12\x17\n\x0fresponseMessage\x18\x02 \x01(\t\"\xab\x02\n\x1dVehicleStartTelemetryResponse\x12\x14\n\x0cresponseCode\x18\x01 \x01(\x05\x12\x17\n\x0fresponseMessage\x18\x02 \x01(\t\x12\x15\n\x08\x61ltitude\x18\x03 \x01(\x05H\x00\x88\x01\x01\x12\x16\n\tlongitude\x18\x04 \x01(\x02H\x01\x88\x01\x01\x12\x15\n\x08latitude\x18\x05 \x01(\x02H\x02\x88\x01\x01\x12\x18\n\x0btemperature\x18\x06 \x01(\x02H\x03\x88\x01\x01\x12\x18\n\x0btimeToOrbit\x18\x07 \x01(\x05H\x04\x88\x01\x01\x12\x19\n\x11transmitTelemetry\x18\x08 \x01(\x08\x42\x0b\n\t_altitudeB\x0c\n\n_longitudeB\x0b\n\t_latitudeB\x0e\n\x0c_temperatureB\x0e\n\x0c_timeToOrbit\"M\n\x1cVehicleStopTelemetryResponse\x12\x14\n\x0cresponseCode\x18\x01 \x01(\x05\x12\x17\n\x0fresponseMessage\x18\x02 \x01(\t2\xce\x02\n\x14LaunchVehicleService\x12:\n\rVehicleLaunch\x12\x0f.VehicleRequest\x1a\x16.VehicleLaunchResponse0\x01\x12\x38\n\rDeployPayload\x12\x0f.VehicleRequest\x1a\x16.DeployPayloadResponse\x12,\n\x07\x44\x65orbit\x12\x0f.VehicleRequest\x1a\x10.DeorbitResponse\x12J\n\x15VehicleStartTelemetry\x12\x0f.VehicleRequest\x1a\x1e.VehicleStartTelemetryResponse0\x01\x12\x46\n\x14VehicleStopTelemetry\x12\x0f.VehicleRequest\x1a\x1d.VehicleStopTelemetryResponseb\x06proto3')



_VEHICLEREQUEST = DESCRIPTOR.message_types_by_name['VehicleRequest']
_VEHICLELAUNCHRESPONSE = DESCRIPTOR.message_types_by_name['VehicleLaunchResponse']
_DEPLOYPAYLOADRESPONSE = DESCRIPTOR.message_types_by_name['DeployPayloadResponse']
_DEORBITRESPONSE = DESCRIPTOR.message_types_by_name['DeorbitResponse']
_VEHICLESTARTTELEMETRYRESPONSE = DESCRIPTOR.message_types_by_name['VehicleStartTelemetryResponse']
_VEHICLESTOPTELEMETRYRESPONSE = DESCRIPTOR.message_types_by_name['VehicleStopTelemetryResponse']
VehicleRequest = _reflection.GeneratedProtocolMessageType('VehicleRequest', (_message.Message,), {
  'DESCRIPTOR' : _VEHICLEREQUEST,
  '__module__' : 'LaunchVehicle_pb2'
  # @@protoc_insertion_point(class_scope:VehicleRequest)
  })
_sym_db.RegisterMessage(VehicleRequest)

VehicleLaunchResponse = _reflection.GeneratedProtocolMessageType('VehicleLaunchResponse', (_message.Message,), {
  'DESCRIPTOR' : _VEHICLELAUNCHRESPONSE,
  '__module__' : 'LaunchVehicle_pb2'
  # @@protoc_insertion_point(class_scope:VehicleLaunchResponse)
  })
_sym_db.RegisterMessage(VehicleLaunchResponse)

DeployPayloadResponse = _reflection.GeneratedProtocolMessageType('DeployPayloadResponse', (_message.Message,), {
  'DESCRIPTOR' : _DEPLOYPAYLOADRESPONSE,
  '__module__' : 'LaunchVehicle_pb2'
  # @@protoc_insertion_point(class_scope:DeployPayloadResponse)
  })
_sym_db.RegisterMessage(DeployPayloadResponse)

DeorbitResponse = _reflection.GeneratedProtocolMessageType('DeorbitResponse', (_message.Message,), {
  'DESCRIPTOR' : _DEORBITRESPONSE,
  '__module__' : 'LaunchVehicle_pb2'
  # @@protoc_insertion_point(class_scope:DeorbitResponse)
  })
_sym_db.RegisterMessage(DeorbitResponse)

VehicleStartTelemetryResponse = _reflection.GeneratedProtocolMessageType('VehicleStartTelemetryResponse', (_message.Message,), {
  'DESCRIPTOR' : _VEHICLESTARTTELEMETRYRESPONSE,
  '__module__' : 'LaunchVehicle_pb2'
  # @@protoc_insertion_point(class_scope:VehicleStartTelemetryResponse)
  })
_sym_db.RegisterMessage(VehicleStartTelemetryResponse)

VehicleStopTelemetryResponse = _reflection.GeneratedProtocolMessageType('VehicleStopTelemetryResponse', (_message.Message,), {
  'DESCRIPTOR' : _VEHICLESTOPTELEMETRYRESPONSE,
  '__module__' : 'LaunchVehicle_pb2'
  # @@protoc_insertion_point(class_scope:VehicleStopTelemetryResponse)
  })
_sym_db.RegisterMessage(VehicleStopTelemetryResponse)

_LAUNCHVEHICLESERVICE = DESCRIPTOR.services_by_name['LaunchVehicleService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VEHICLEREQUEST._serialized_start=23
  _VEHICLEREQUEST._serialized_end=60
  _VEHICLELAUNCHRESPONSE._serialized_start=62
  _VEHICLELAUNCHRESPONSE._serialized_end=174
  _DEPLOYPAYLOADRESPONSE._serialized_start=176
  _DEPLOYPAYLOADRESPONSE._serialized_end=246
  _DEORBITRESPONSE._serialized_start=248
  _DEORBITRESPONSE._serialized_end=312
  _VEHICLESTARTTELEMETRYRESPONSE._serialized_start=315
  _VEHICLESTARTTELEMETRYRESPONSE._serialized_end=614
  _VEHICLESTOPTELEMETRYRESPONSE._serialized_start=616
  _VEHICLESTOPTELEMETRYRESPONSE._serialized_end=693
  _LAUNCHVEHICLESERVICE._serialized_start=696
  _LAUNCHVEHICLESERVICE._serialized_end=1030
# @@protoc_insertion_point(module_scope)
